[package]
name = "five-d-chess"
version = "0.1.0"
edition = "2021"

[lib]  
crate-type = ["cdylib", "rlib"]

[dependencies]
num_enum = "0.6.1"
deku = "0.16"
wasm-bindgen = "0.2.87"
web-sys = "0.3.64"
serde = { version = "1.0.170", features = ["derive"] }
serde_json = "1.0"
js-sys = "0.3.64"

